import "@/styles/globals.css";
import { Metadata } from "next";
import { Providers } from "./providers";
import  NavBar  from "@/components/nav/navbar";
import { Link } from "@nextui-org/link";
import { Poppins } from 'next/font/google'
import Footer from "@/components/footer/Footer";
import CartProvider from "@/providers/CartProviders";
import { Toaster } from "react-hot-toast";


const poppins = Poppins({ subsets: ['latin'], 
weight : ['400', '700'] })

export const metadata: Metadata = {
	title: 'Sistem Informasi Perpustakaan Pusaka',
	description: 'Generated by Kelompok 2 RPL',
	icons: {
		icon: "/favicon.ico",
		shortcut: "/favicon-16x16.png",
		apple: "/apple-touch-icon.png",
	},
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className=
				{`${poppins.className} text-slate-700 light`}>
				<Providers>
					<Toaster toastOptions={{
						style:{
							background: 'rgb(51 65 85)',
							color: '#fff'
						}
					}}/>
					<CartProvider>
				<div className='light flex flex-col min-h-screen'>
						<NavBar />
						<main className='light flex-grow'>{children}</main>
						<Footer/>
					</div>
					</CartProvider>
				</Providers>
			</body>
		</html>
	);
}
